branches:
  except:
    - gh-pages
sudo: required
language: node_js
node_js:
  - "10"
install: npm install
cache:
  directories: 
    - $HOME/.npm
jobs:
  include:
    # 代码检查
    - stage: lint
      script: npm run lint
    # 代码编译
    - stage: compile
      script: npm run compile
    # 执行测试
    - stage: test
      script: npm run test  -- --coverage && bash <(curl -s https://codecov.io/bash)
    # 编译文档
    - stage: site
      script: npm run site:build
    # 检查tag是否与version匹配
    - stage: check_tag
      script: node script/ci/check_tag.js
    # 自动发布版本到npm
    - stage: publish
      script: npm publish
    # 自动发布文档
    - stage: deploy
      script: skip
      deploy: 
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs/dist
        target_branch: gh_pages
stages:
  - lint
  - compile
  - test
  - site
  - name: check_tag
    if: tag IS present
  - name: publish
    if: tag IS present
  - name: deploy
    if: tag IS present