branches:
  except:
    - gh-pages
sudo: required
language: node_js
node_js:
  - "10"

install: npm install

script:
  - npm run lint
  - ./script/ci/test.sh
  - npm run compile
  - npm run site:build

deploy:
  - provider: npm
    skip_cleanup: true
    email: xrs4433@outlook.com
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./docs
    target_branch: gh_pages
    on:
      tags: true
