branches:
  except:
    - gh-pages
sudo: required
language: node_js
node_js:
  - "10"
install: npm install
cache: npm
jobs:
  include:
    # 代码检查
    - stage: lint
      script: npm run lint
      name: lint
    # 执行测试
    - stage: test
      script: ./script/ci/test.sh
      name: test
    # 编译
    - stage: compile
      script: npm run compile
      name: compile
    - script: npm run dist
      name: dist
    # 编译发布文档
    - stage: docs
      script: npm run docs
      name: docs
      deploy:
        - provider: npm
          skip_cleanup: true
          email: xrs4433@outlook.com
          api_key: $NPM_TOKEN
          on:
            tags: true
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./docs
          target_branch: gh-pages
          on:
            tags: true
