sudo: required
language: node_js
node_js:
  - "10"
install: npm install
cache:
  directories:
    - $HOME/.npm
matrix:
  fast_finish: true
  include:
    - env: REACT=16 TEST_TYPE=test:dom

script: 
  - npm run tslint
  - npm run test -- --collectCoverage
  - npm run compile
  - npm run dist
