name: Test And Build
on: 
  pull_request:
  push:
    branches:
      - master
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: npm install
    - name: lint:es
      run: npm run lint:es
    - name: lint:style
      run: npm run lint:style
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: npm install
    - name: test
      run: npm run test -- --coverage --bail
    - name: codacy-coverage
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{secrets.CODACY_TOKEN}}
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: npm install
    - name: compile:lib
      run: npm run compile:lib
    - name: compile:es
      run: npm run compile:es
  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: npm install
    - name: dist
      run: npm run dist
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: npm install
    - name: docs
      run: npm run docs