name: build
on:
  pull_request:
  push:
    branches:
      - master
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm install && npm run bootstrap

      - name: lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm install && npm run bootstrap

      - name: test
        run: npm run test -- --coverage --bail

      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: codacy-coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{secrets.CODACY_TOKEN}}

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm install && npm run bootstrap

      - name: compileEs
        run: npm run compileEs

      - name: compileLib
        run: npm run compileLib

  dist:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm install && npm run bootstrap

      - name: dist
        run: npm run dist
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm install && npm run bootstrap

      - name: docs
        run: npm run docs
